#pragma config(Sensor, in4,    lightSensor,         sensorLineFollower)
#pragma config(Sensor, in2,    encoderIN2,          sensorRotation)
#pragma config(Sensor, in3,    encoderIN3,          sensorRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*************************************************************************
	Right Motor 		- port2
	Left	Motor 		- port3
	Ambient Light		- in4

- Lighting conditions change from place to place, so the value 200 may
	need to be changed to better suit your environment.
*************************************************************************/
bool fl = true; //Used to determine which direction flail turns towards
int i = 0; //Used in for loops

void go(){
	fl = true;
	motor[port3] = 40;
	motor[port2] = 40;
	wait1Msec(100);
}


void flail(){
	if (fl == true){
		motor[port2] = 40;
		motor[port3] = -40;

		for (i = 0; i < 99; i++){
			wait1Msec(10);
			if (SensorValue(lightSensor) < 200){break;}
		}

		fl = false;
	}else{
		motor[port2] = -60;
		motor[port3] = 60;
		for (i = 0; i < 199; i++){
			wait1Msec(10);
			if (SensorValue(lightSensor) < 200){break;}
		}
		fl = true;
	}
}

task main(){

	wait1Msec(2000);						//Robot waits for 2000 milliseconds before executing program
	bMotorReflected[port2] = true;	//Reflects the direction of the motor on port2

	while(true){
		while (SensorValue(lightSensor) < 200) {go();} //Go when it's light.
		while (SensorValue(lightSensor) >= 200) {flail();} //Go when it's dark.
	}
}

/*
bool wantToDie = true;
if(programWorks == true){wantToDie = false}
*/
