#pragma config(Sensor, in4,    lineTracker4,         sensorLineFollower)
#pragma config(Sensor, in5,    lineTracker5,         sensorLineFollower)
#pragma config(Sensor, in6,    lineTracker6,         sensorLineFollower)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*************************************************************************
VEX - Line Track

Description: This program instructs the robot to follow a line forever, by
using an infinite while loop. There is a two second pause at the beginning
of the program.

Configuration: This program is written to work with a modified version of
the Squarebot model.
	Right Motor 		- port2
	Left	Motor 		- port3
	Line Follower		- in1

Additional Notes:
-	The "bMotorReflected[port2] = 1;" is needed with the Squarebot model,
	but may not be needed for all robot configurations.
- Lighting conditions change from place to place, so the value 950 may
	need to be changed to better suit your environment.
*************************************************************************/

task main()
{
	wait1Msec(2000);								//Robot waits for 2000 milliseconds before executing program
	bMotorReflected[port2] = true;			//Reflects the direction of the motor on port2

	while(true)        //Follow the line forever
	{
		if (SensorValue(lineTracker4) < 900)
		{

			motor[port2] = 60;
      motor[port3] = 0;
		}
		else if (SensorValue(lineTracker6) < 1200)
		{
			//Turn Right
      motor[port2] = 0;
      motor[port3] = 60;
		}
		else{
			motor[port2] = 40;
      motor[port3] = 40;
		}
	}
}
