#pragma config(Sensor, in2,    encoderIN2,          sensorRotation)
#pragma config(Sensor, in3,    encoderIN3,          sensorRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*************************************************************************
Configuration: This program is written to work with a modified version of
the Squarebot model.
	Right Motor 		- port2
	Left	Motor 		- port3

Additional Notes:
-	The "bMotorReflected[port2] = true;" is useful with the Squarebot model.
	Right Encoder		- in2
	Left  Encoder		- in3
*************************************************************************/

void go(int rotations)
{
	SensorValue[encoderIN3] = 0;	//Set the encoder so that it starts counting at 0
	SensorValue[encoderIN2] = 0;	//Set the encoder so that it starts counting at 0

	while(SensorValue[encoderIN2] < rotations && SensorValue[encoderIN3] < rotations)
	{

		if(SensorValue[encoderIN2] < SensorValue[encoderIN3]) //If it's veering to the right. Stops before the limits.
		{
			motor[port3] = 40;
			motor[port2] = 60;

		}else if(SensorValue[encoderIN2] > SensorValue[encoderIN3]) //Veering left.
		{
			motor[port3] = 60;
			motor[port2] = 40;

		}else
		{
			motor[port3] = 60;
			motor[port2] = 60;
		}
		wait1Msec(25);
	}
}

void lTurn()
{
	SensorValue[encoderIN3] = 0;	//Set the encoder so that it starts counting at 0
	SensorValue[encoderIN2] = 0;	//Set the encoder so that it starts counting at 0

	while(SensorValue[encoderIN2] < 195)
	{
		motor[port2] = 93;
		motor[port3] = 0;
		wait1Msec(1);
	}
}

void rTurn()
{
	SensorValue[encoderIN3] = 0;	//Set the encoder so that it starts counting at 0
	SensorValue[encoderIN2] = 0;	//Set the encoder so that it starts counting at 0

	while(SensorValue[encoderIN3] < 215)
	{
		motor[port3] = 93;
		motor[port2] = 0;
		wait1Msec(1);
	}
}

task main()
{
	wait1Msec(2000);							//Robot waits for 2000 milliseconds before executing program
	bMotorReflected[port2] = true;		//Reflects the direction of the motor on port2

	go(250);
	rTurn();
	go(150);
	rTurn();
	go(40);
	rTurn();
	go(30);
	lTurn();
	go(50);
	lTurn();
	go(130);

}
